
title: thoughts on physics
description: philosophical conjectures reduced to haiku poems

github:
  is_user_page: false
  is_project_page: false

remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
